# Numpy Tutorial

In [1]:
import numpy as np

Lets create an array.
np.arange() creates an array for given range.
reshape() is used to define the demension of array,
here 2,5 means 2 arrays containing 5 elements.

In [3]:
arr = np.arange(10,dtype=float).reshape(2,5)

In [4]:
print(arr.shape)

(2, 5)


In [5]:
arr

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

Create an another array.
here se we have given a range 10 to 100, the other 2 is the step, means go from 10 to 100 with the interval of 2.

In [6]:
arr2=np.arange(10,100,2)

In [7]:
arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [8]:
type(arr2)

numpy.ndarray

In [9]:
arr2.dtype

dtype('int32')

In [10]:
arr2.shape

(45,)

In [11]:
arr2.size

45

You can also think of 1D and 2D arrays.

In [13]:
oneD=np.arange(1,100)

In [14]:
oneD

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
twoD = np.arange(96,dtype=float).reshape(12,8)

In [20]:
twoD

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.],
       [32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47.],
       [48., 49., 50., 51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60., 61., 62., 63.],
       [64., 65., 66., 67., 68., 69., 70., 71.],
       [72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87.],
       [88., 89., 90., 91., 92., 93., 94., 95.]])

You can also create an array of ones and zeros. means value will 1 or 0 already.

In [21]:
k = np.ones(10,dtype=int)

In [22]:
k

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
kz = np.zeros(10,dtype=np.int)

In [24]:
kz

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
type(k)

numpy.ndarray

In [26]:
type(kz)

numpy.ndarray

In [27]:
k.dtype

dtype('int32')

In [28]:
kz.dtype

dtype('int32')